spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pos_bit?useSSL=false
    username: root
    password: "@My#db2025!"

  jpa:
    hibernate:
      ddl-auto: create

jwt:
  secret: your-very-long-secure-random-secret-at-least-43-chars-please-2026